version: '2'
services:
    demo-app:
        image: demo
        external_links:
            - demo-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/demo?useUnicode=true&characterEncoding=utf8&useSSL=false
        ports:
            - 8080:8080
    demo-mysql:
        extends:
            file: mysql.yml
            service: demo-mysql
